config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}, controllers: {registrations: "user_registrations"}
  resources :users
  resources :products do
    resources :comments
  end
  resources :orders, only: [:index, :show, :create, :destroy]
  
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  get 'static_pages/payment_thank_you'
  
  root 'static_pages#landing_page'

  get 'users/new'

  get 'products/index'

  post 'static_pages/thank_you'

  post 'payments/create'

  mount ActionCable.server => '/cable'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def landing_page
  	@products = Product.limit(3)
  end

  def thank_you
  	@name = params[:name]
  	@email = params[:email]
  	@message = params[:message]
    UserMailer.contact_form(@email, @name, @message).deliver
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<div class="container-fluid">
	<h1>About</h1>
	<p>Working through the process of creating an
   	app using Ruby on Rails, as part of Career Foundry's
   	Web Developer course.
	</p>	
</div>

app/views/static_pages/contact.html.erb
<h1 style="text-align: left; color: grey">Contact Us</h1>

<%= flash[:notice] %>

<%= form_tag("/static_pages/thank_you") do %>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= text_field_tag :name, nil, class: "form-control pull-left", placeholder: "Enter Name", required: true %>
      </div>
      <div class="form-group">
        <%= text_field_tag :email, nil, class: "form-control pull-left", placeholder: "Enter Email", required: true %>
      </div>
      <div class="form-group">
        <%= text_area_tag :message, nil, class: "form-control pull-left", placeholder: "Enter Message", required: true %>
      </div>
    </div>
  </div>
  <%= submit_tag "Send", class: "btn btn-default pull-left" %>
<% end %>

app/views/static_pages/index.html.erb
<div class="container-fluid">

	<h1>10 Pin Action Pro Shop</h1>
	<h2>Your friendly, local pro shop here to meet all your bowling needs!</h2>

	<hr>

	<%= image_tag("cobra.jpg", class: "img-responsive prod-list") %>
	<%= image_tag("venom-shock.jpg", class: "img-responsive prod-list") %>
	<%= image_tag("ghost.jpg", class: "img-responsive prod-list") %>
	<br>
	<br>
	<%= image_tag("jackel-le.jpg", class: "img-responsive prod-list") %>
	<%= image_tag("octane-burn.jpg", class: "img-responsive prod-list") %> 
	<%= image_tag("octane-carbon.jpg", class: "img-responsive prod-list") %>
</div>

app/views/static_pages/landing_page.html.erb
<h2>Featured Product:</h2>
<hr>
<!-- Product Carousel -->
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
	<!-- Indicators -->
	<ol class="carousel-indicators">
		<% (0..@products.count-1).each do |i| %>
			<li data-target="#carousel-example-generic" data-slide-to="<%= i % @products.count %>" 			class="<%= " active" if i == 0%>"></li>
		<% end %>
	</ol>

	<!-- Wrapper for slides -->
	
	<div class="carousel-inner" role="listbox">
		<% @products.each do |product| %>
		<div class="item<%= " active" if product == @products.first %>" align="middle">
		  <%= image_tag(product.image_URL) %>
		  <div class="carousel-caption">
		  	<h2><%= product.name %></h2>
		  </div><!--  end carousel-caption -->
		</div><!-- end item -->
		<% end %>
	</div><!-- end carousel-inner -->

	<!-- Controls -->
	<a class="left carousel-control" href="#carousel-example-generic"
	   role="button" data-slide="prev">
		<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
		<span class="sr-only">Previous</span>
	</a>
	<a class="right carousel-control" href="#carousel-example-generic"
		 role="button" data-slide="next">
	  <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
	  <span class="sr-only">Next</span>
	</a> 
</div><!--  end of carousel -->

app/views/static_pages/payment_thank_you.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-md-6 col-xs-12 thankyou_note">
      <p class="product_title"> Thank you for your purchase!</p>
      <p class="create_text"> Be sure to leave us a <%=link_to 'comment', product_path(@product)%>. </p>
      <p class="create_text">  Browse through our other <%= link_to 'bikes!', products_path %> </p>
    </div>
  </div>
</div>

app/views/static_pages/thank_you.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <p>Thank you. We have received your message and will respond as soon as possible.</p>
  </div><!-- / panel-body -->
</div><!-- / panel -->

<%= link_to 'Home', root_path %>