config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}, controllers: {registrations: "user_registrations"}
  resources :users
  resources :products do
    resources :comments
  end
  resources :orders, only: [:index, :show, :create, :destroy]
  
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  get 'static_pages/payment_thank_you'
  
  root 'static_pages#landing_page'

  get 'users/new'

  get 'products/index'

  post 'static_pages/thank_you'

  post 'payments/create'

  mount ActionCable.server => '/cable'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App1</title>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'%>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquey.min.js"></script>
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

  </head>

  <body>
    <!-- navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
  
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="              .navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="projectName navbar-brand">
          <%= link_to 'Bowling Pro Shop', root_path %>
        </div><!-- end navbar-brand -->
      </div> <!-- end navbar-header -->
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'About', static_pages_about_path %></li>
          <li><%= link_to "Products", products_path %><li>
          <li><%= link_to 'Contact', static_pages_contact_path %></li>
          <li>
            <!-- Search Box -->
            <%= form_tag("/products", method: "get", class:"navbar-form navbar-right") do %> 
            <div class="form-group">
              <%= label_tag(:q, "Search for:", class:"hidden") %>
              <%= text_field_tag(:q, "", type:"text", class:"form-control", placeholder:"Search") %>
            </div>
            <%= submit_tag("Search", class:"btn btn-default") %>
            <% end %>
          </li>
          <li>
            <% if user_signed_in? %>
              <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
            <% else %>
              <%= link_to('Login', new_user_session_path) %>
              <li>
                <%= link_to('Sign Up', new_user_registration_path) %>
              </li>
            <% end %>
          </li>
        </ul>
      </div><!-- end navbar-collapse -->
    </nav> <!-- end navbar --> 

    <!--Flash Notice-->
    <% if notice %>
      <div id="notice" class="alert alert-warning"><%= notice %></div>
    <% end %>
    <% if alert %>
      <div id="alert" class="alert alert-danger"><%= alert %></div>
    <% end %>

    <%= yield %>

    <hr>

    <footer id="footer" class="footer">
        <p>&copy; 2017 10 Pin Action Pro Shop. All rights reserved.</p>
    </footer>

  </body>
</html>